version: '3.4'

services:
  Jenner.Consultar.Worker:
    image: ${DOCKER_REGISTRY-}jennerconsultarworker
    build:
      context: .
      dockerfile: src/Jenner.Consultar.Worker/Dockerfile

  Jenner.Consultar.API:
    image: ${DOCKER_REGISTRY-}jennerconsultarapi
    build:
      context: .
      dockerfile: src/Jenner.Consultar.API/Dockerfile

  Jenner.Agendamento.API:
    image: ${DOCKER_REGISTRY-}jenneragendamentoapi
    build:
      context: .
      dockerfile: src/Jenner.Agendamento.API/Dockerfile

  Jenner.Aplicacao.API:
    image: ${DOCKER_REGISTRY-}jenneraplicacaoapi
    build:
      context: .
      dockerfile: src/Jenner.Aplicacao.API/Dockerfile

  Jenner.Carteira.API:
    image: ${DOCKER_REGISTRY-}jennercarteiraapi
    build:
      context: .
      dockerfile: src/Jenner.Carteira.API/Dockerfile
