apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-consultar
  labels:
    app: consultar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app-consultar
  template:
    metadata:
      labels:
        app: consultar
        service: app-consultar
    spec:
      containers:
        - name: app-consultar
          image: ghcr.io/guigoetten/jenner/jennercarteira:master
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "600Mi"
              cpu: "1.0"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Deployment
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ConnectionStrings__KafkaBootstrap
              value: kafka-service:29092
            - name: ConnectionStrings__MongoDb
              value: mongodb+srv://jennermicroservices:B7fGAyzi3ZqJ7C4u@jennermicroservices.1mnmk4v.mongodb.net/?retryWrites=true&w=majority
---
apiVersion: v1
kind: Service
metadata:
  name: app-consultar-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: app-consultar