apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-agendar
  labels:
    app: agendar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: app-agendar
  template:
    metadata:
      labels:
        app: agendar
        service: app-agendar
    spec:
      containers:
        - name: app-agendar
          image: ghcr.io/guigoetten/jenner/jenneragendamento:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Deployment
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ConnectionStrings__KafkaBootstrap
              value: kafka-service:29092
            - name: ConnectionStrings__MongoDb
              value: mongodb://root:imroot@mongo-db:27017/
---
apiVersion: v1
kind: Service
metadata:
  name: app-agendar-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: app-agendar