name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: "Extract Branch name"
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      
    - name: Build Container Image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
      
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.GH_PACKAGES_TOKEN2 }}" | docker login https://ghcr.io -u ${{ github.actor }}} --password-stdin
          
    - name: "Tentando publicar"
      run: |
        ImageId=ghcr.io/guigoetten/jenner/jenneragendamento:${{ github.sha }}
        docker push $ImageId
