name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: "Extract Branch name"
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      
    - name: Build Container Image
      run: docker build . --file ./src/Jenner.Agendamento.API/Dockerfile --tag teste
      
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.CM_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }}} --password-stdin
      
    - name: Images
      run: docker images
          
    - name: "Tentando publicar"
      run: |
        ImageId=teste:latest
        docker push $ImageId
