name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: "Extract Branch name"
      run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: "Login to GitHub registry"
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    
    - name: "Publish the image Jenner.Agendamento.Api"
      uses: docker/build-push-action@v2
      with:
        file: ./src/Jenner.Agendamento.API/Dockerfile
        context: .
        push: true
        tags: |
          ghcr.io/guigoetten/jenner/jenneragendamento:${{ github.sha }}
          ghcr.io/guigoetten/jenner/jenneragendamento:${{ env.BRANCH }}
    
    - name: "Publish the image Jenner.Aplicacao.Api"
      uses: docker/build-push-action@v2
      with:
        file: ./src/Jenner.Aplicacao.API/Dockerfile
        context: .
        push: true
        tags: |
          ghcr.io/guigoetten/jenner/jenneraplicacao:${{ github.sha }}
          ghcr.io/guigoetten/jenner/jenneraplicacao:${{ env.BRANCH }}

    - name: "Publish the image Jenner.Carteira.Api"
      uses: docker/build-push-action@v2
      with:
        file: ./src/Jenner.Carteira.API/Dockerfile
        context: .
        push: true
        tags: |
          ghcr.io/guigoetten/jenner/jennercarteira:${{ github.sha }}
          ghcr.io/guigoetten/jenner/jennercarteira:${{ env.BRANCH }}
          
    - name: "Publish the image Jenner.Carteira.Agendador.Worker.Api"
      uses: docker/build-push-action@v2
      with:
        file: ./src/Jenner.Carteira.Agendador.Worker/Dockerfile
        context: .
        push: true
        tags: |
          ghcr.io/guigoetten/jenner/jennercarteiraagendadorworker:${{ github.sha }}
          ghcr.io/guigoetten/jenner/jennercarteiraagendadorworker:${{ env.BRANCH }}   
          
